const fieldLabels = {
    english: {
      districtNumber: "District Number / Section",
      settlementNumber: "Settlement Number",
      serviceSettlementNumber: "Service Settlement Number",
      businessCollegeNumber: "Business and College Branch Number",
      settlementBranchNumber: "Settlement Branch Number",
      serviceWorkerBranchNumber: "Service Worker Branch Number",
      totalServiceWorkers: "Total Service Workers",
      totalServiceWork: "Total Service Work (Including Service Work of Organizations)",
      monthlyContactNumber: "Monthly Contacting Settlement Branch Number",
      villagesAbove5000: "Villages with Population greater than 5000",
      businessVillageNumber: "Business or Farmer Branch Village Number",
      serviceVillageNumber: "Service-Enabled Village Number",
      totalServiceInVillages: "Total Service Work in Villages",
      villagesOver5000: "Villages with Population greater than 5000",
      villagesUnder5000: "Service-Enabled Villages with Population less than 5000",
      totalServiceInVillagesBelow5000: "Total Service Work in Villages with Population less than 5000",
      selectNagar: "Select Nagar Type",
      mahanagar: "Mahanagar",
      jilaKendra: "Jila Kendra",
      anyaNagar: "Anya Nagar",
      selectLanguage:"Select Language : ",
      profile:"Profile",
      logout:"Logout",
      saveAsSubmit:"Save As Submit",
      Login:"Login",
      Username:"Username",
      EnterYourUsername:"Enter Your Username",
      Password:"Password",
      EnterYourPassword:"Enter Your Password",
      PrantName:"Prant Name",
      TotalVibhag:"Total Vibhag",
      TotalJila:"Total Jila",
      PrantUsers:"Prant Users",
      Prant: "Prant",
      FULLNAME:"Full Name",
      EMAIL:"Email",
      MOBILE:"Mobile No.",
      Dashboard:"Dashbaord",
      Reporting:"Reporting",
      ViewForm:"View From",
      ViewReporting:"View Reporting",
      UserManagement:"User Management",
      CreateUser:"Create User",
      ViewUsers:"View Users",
      ViewActivity:"View Activity",
      UserList:"Users List",
      UserType:"UserType",
      Kendra:"Kendra",
      Kshetra:"Kshetra",
      Vibhag:"Vibhag",
      Jila:"Jila",
      GrandTotal:"Grand Total",
      SelectUserType:"Select User Type",
      Phone:"Phone",
      Level:"Level",
      SelectLevel:"Select Level",
      SelectKshetra:"Select Kshetra",
      SelectPrant:"Select Prant",
      SelectVibhag:"Select Vibhag",
      SelectJila:"Select Jila",
      SelectKshetra:"Select Kshetra",
      English:"English",
      Hindi:"Hindi",
      ToatalKshetra:"Toatal Kshetra",
      ToatalPrant:"Toatal Prant",
      NoDataAvailable:"No Data Available",
      SaveAsSubmit:"Save As Submit",
      Submit:"Submit",
      selectVibhag:"Select Vibhag ",
      selectJila:"Select Jila",
      KshetraPrantVibahgJila:"Kshetra / Prant / Vibahg / Jila",
      NoUsersAvailable:"No Users Available",
      TableVillagesOver5000:"More than 5000",
      TableVillagesUnder5000:"Less than 5000",
      AreaType:"Area Type"
       },


    
    

    hindi: {
      districtNumber: "जिला सम महानगर/भाग संख्या",
      settlementNumber: "इनमें सेवा बस्ती संख्या",
      serviceSettlementNumber: "सेवा कार्य युक्त सेवा बस्ती",
      businessCollegeNumber: "व्यवसायी व महाविद्यालय शाखा व मिलन संख्या",
      settlementBranchNumber: "सेवा बस्ती पालक शाखा व मिलन संख्या",
      serviceWorkerBranchNumber: "सेवा कार्यकर्ता युक्त शाखा व मिलन संख्या",
      totalServiceWorkers: "कुल सेवा कार्यकर्ता",
      totalServiceWork: "महानगर में कुल सेवा कार्य (सेवा संस्थाओं के सेवा कार्य सहित)",
      monthlyContactNumber: "मासिक सेवा बस्ती संपर्क करने वाली शाखा व मिलन संख्या",
      villagesAbove5000: "5000 या उससे अधिक जनसंख्या के ग्रामों की संख्या",
      businessVillageNumber: "इनमें व्यवसायी या कृषक शाखायुक्त ग्राम",
      serviceVillageNumber: "इनमें सेवा कार्ययुक्त ग्राम",
      totalServiceInVillages: "इनमें कुल सेवा कार्य",
      villagesOver5000: "5000 से अधिक जनसंख्या के ग्राम",
      villagesUnder5000: "5000 से कम जनसंख्या के ग्राम ",
      totalServiceInVillagesBelow5000: "इनमें कुल सेवा कार्य",
      selectNagar: "नगर प्रकार चुनें",
      mahanagar: "महानगर",
      jilaKendra: "जिलाकेंद्र",
      anyaNagar: "अन्य नगर",
      selectLanguage:"भाषा चयन करें :",
      profile:"प्रोफ़ाइल",
      logout:"लॉगआउट",
      saveAsSubmit:"सहेजें और सबमिट करें",
      Login:"लॉगिन",
      Username:"उपयोगकर्ता नाम",
      EnterYourUsername:"अपना उपयोगकर्ता नाम दर्ज करें",
      Password:"पासवर्ड",
      EnterYourPassword:"अपना पासवर्ड दर्ज करें",
      PrantName:"प्रांत का नाम",
      TotalVibhag:"कुल विभाग",
      TotalJila:"कुल जिला",
      PrantUsers:"प्रांत के उपयोगकर्ता",
      Prant: "प्रांत",
      FULLNAME:"पूरा नाम",
      EMAIL:"ईमेल",
      MOBILE:"मोबाइल नंबर",
      Dashboard:"डैशबोर्ड",
      Reporting:"रिपोर्टिंग",
      ViewForm:"फॉर्म देखें",
      ViewReporting:"रिपोर्टिंग देखें",
      UserManagement:"उपयोगकर्ता प्रबंधन",
      CreateUser:"उपयोगकर्ता बनाएं",
      ViewUsers:"उपयोगकर्ताओं को देखें",
      ViewActivity:"View Activity",
      UserList:"उपयोगकर्ताओं की सूची",
      UserType:"उपयोगकर्ता प्रकार",
      Kendra:"केंद्र",
      Kshetra:"क्षेत्र",
      Vibhag:"विभाग",
      Jila:"जिला",
      GrandTotal:"कुल योग",
      SelectUserType:"उपयोगकर्ता प्रकार चुनें",
      Phone:"फोन",
      Level:"स्तर",
      SelectLevel:"स्तर चुनें",
      SelectKshetra:"क्षेत्र चुनें",
      SelectPrant:"प्रांत चुनें",
      SelectVibhag:"विभाग चुनें",
      SelectJila:"जिला चुनें",
      SelectKshetra:"क्षेत्र चुनें",
      English:"English",
      Hindi:"हिंदी",
      ToatalKshetra:"कुल क्षेत्र",
      ToatalPrant:"कुल प्रांत",
      NoDataAvailable:"कोई डेटा उपलब्ध नहीं है",
      SaveAsSubmit:"सहेजें और सबमिट करें",
      Submit:"सबमिट करें",
      selectVibhag:"विभाग चयन करें ",
      selectJila:"जिला चयन करें",
      KshetraPrantVibahgJila:"क्षेत्र / प्रांत / विभाग / जिला",
      Name:"नाम",
      Username:"उपयोगकर्ता नाम",
      UserType:"उपयोगकर्ता प्रकार",
      AreaType:"क्षेत्र प्रकार",
      NoUsersAvailable:"कोई उपयोगकर्ता उपलब्ध नहीं है",
      TableVillagesOver5000:"5000 से अधिक",
      TableVillagesUnder5000:"5000 से कम"
   },
    };

  export default fieldLabels;