const fieldLabels = {
    english: {
      districtNumber: "District Number / Section",
      settlementNumber: "Settlement Number",
      serviceSettlementNumber: "Service Settlement Number",
      businessCollegeNumber: "Business and College Branch Number",
      settlementBranchNumber: "Settlement Branch Number",
      serviceWorkerBranchNumber: "Service Worker Branch Number",
      totalServiceWorkers: "Total Service Workers",
      totalServiceWork: "Total Service Work (Including Service Work of Organizations)",
      monthlyContactNumber: "Monthly Contacting Settlement Branch Number",
      villagesAbove5000: "Villages with Population greater than 5000",
      businessVillageNumber: "Business or Farmer Branch Village Number",
      serviceVillageNumber: "Service-Enabled Village Number",
      totalServiceInVillages: "Total Service Work in Villages",
      villagesOver5000: "Villages with Population less than 5000",
      villagesUnder5000: "Service-Enabled Villages with Population less than 5000",
      totalServiceInVillagesBelow5000: "Total Service Work in Villages with Population less than 5000",
      selectNagar: "Select Nagar Type",
      mahanagar: "Mahanagar",
      jilaKendra: "Jila Kendra",
      anyaNagar: "Anya Nagar",
    },
    hindi: {
      districtNumber: "जिला सम महानगर/भाग संख्या",
      settlementNumber: "इनमें सेवा बस्ती संख्या",
      serviceSettlementNumber: "सेवा कार्य युक्त सेवा बस्ती",
      businessCollegeNumber: "व्यवसायी व महाविद्यालय शाखा व मिलन संख्या",
      settlementBranchNumber: "सेवा बस्ती पालक शाखा व मिलन संख्या",
      serviceWorkerBranchNumber: "सेवा कार्यकर्ता युक्त शाखा व मिलन संख्या",
      totalServiceWorkers: "कुल सेवा कार्यकर्ता",
      totalServiceWork: "महानगर में कुल सेवा कार्य (सेवा संस्थाओं के सेवा कार्य सहित)",
      monthlyContactNumber: "मासिक सेवा बस्ती संपर्क करने वाली शाखा व मिलन संख्या",
      villagesAbove5000: "5000 या उससे अधिक जनसंख्या के ग्रामों की संख्या",
      businessVillageNumber: "इनमें व्यवसायी या कृषक शाखायुक्त ग्राम",
      serviceVillageNumber: "इनमें सेवा कार्ययुक्त ग्राम",
      totalServiceInVillages: "इनमें कुल सेवा कार्य",
      villagesOver5000: "5000 से कम जनसंख्या के ग्रामों की संख्या",
      villagesUnder5000: "इनमें सेवा कार्ययुक्त ग्राम",
      totalServiceInVillagesBelow5000: "इनमें कुल सेवा कार्य",
      selectNagar: "नगर प्रकार चुनें",
      mahanagar: "महानगर",
      jilaKendra: "जिलाकेंद्र",
      anyaNagar: "अन्य नगर",
    },
  };
  
  export default fieldLabels;